//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("SushiHangover.RealmThread")]
[assembly: AssemblyVersion("0.2.1")]
[assembly: AssemblyFileVersion("0.2.1")]
[assembly: AssemblyInformationalVersion("0.2.1+2.Branch.master.Sha.078b3f51aa54f581109a143f27d9b5802fda3a1d")]
[assembly: AssemblyCopyright("Copyright (c) SushiHangover/RobertN")]

