//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("SushiHangover.RealmThread")]
[assembly: AssemblyVersion("0.1.2")]
[assembly: AssemblyFileVersion("0.1.2")]
[assembly: AssemblyInformationalVersion("0.1.2+6.Branch.master.Sha.e4edaea96fd50ab6ea435e44ca45cad6d7f4276e")]
[assembly: AssemblyCopyright("Copyright (c) SushiHangover/RobertN")]

