//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("SushiHangover.RealmThread")]
[assembly: AssemblyVersion("0.1.2")]
[assembly: AssemblyFileVersion("0.1.2")]
[assembly: AssemblyInformationalVersion("0.1.2+7.Branch.master.Sha.db245fc8bd843b6276c6093e011fced44a94ab43")]
[assembly: AssemblyCopyright("Copyright (c) SushiHangover/RobertN")]

